### PR TITLE
CCS scenario - CCSCO2 emission added, emission limit and emission act…

### PR DESCRIPTION
**Pull request by EmiFej**
Added EMISSION: CCSC02
For each CS technology, with a negative (-) value for CO2 emissions, I added a the same number but positive (+) as EmissionActivityRatio with CCSCO2 as emission. 
Norway (NO) and Switzerland (CH) were excluded from the CCSCO2 EmissionActivity values. 
All emissions from CS (both CO2 and CCSCO2) were recalculated to Mt instead of kt (even for NO/CH). 
AnnualEmissionLimit for CCSCO2 emission set to 250 Mt annually for 2015-2060.

### CODE REVIEW

**Comment by HauHe** [comment]
First of a small comment for keeping the repo clean. Please don't commit these .DS_Store files.

**Comment by HauHe** [comment]
I can't see the data in the file EmissionAtivityRatio, but since you write that you converted the values to mt I assume they are correct.
You just converted the ones for CCSCO2 to mt right?

**Comment by EmiFej** [comment]
This is an example of the EmissionActivityRatio input. Positive values in Mt. 
I did change the kt to Mt for all the CO2 emissions (negative, -) that have CCS and a limit, so not just the CCSCO2. 

Screenshot 2022-01-26 at 11 30 49

**Comment by HauHe** [comment]
That will create a problem. For now I would leave them in kt. Since they are accounted in the emission CO2 they have to be in the same unit as the other CO2 emission and the CO2 Emission Limit and the EmissionPenalty.
Hence I would say:
- CCSCO2 in Mt
- CO2 in kt

**Pull request merged**
