### PR TITLE
Removed previous files that were wrongfully pushed

### PR DESCRIPTION
**Pull request by EmiFej**
Removed previous data files for the WP1_NetZero scenario which were previously wrongfully pushed and merged. They were used to check different EmissionPenalties.

### CODE REVIEW

**Comment by HauHe** [comment]
Hi @EmiFej ,
thanks for cleaning this up.
I see you removed 8 files, but in the folder I count 9. Do you want to keep one datafile?
Shouldn't we just keep the folder of csv-files?

**Comment by EmiFej** [comment]
Hi @HauHe, if you wish I can remove it too. Since we had a datafile in all the folders for the WP1 scenarios (including WP1_LimBio, WP1_LimNuclear etc.) I understood it that we wanted to have them. Let me know and I can remove them from all WP1 folders.

**Comment by HauHe** [comment]
Yes, please remove them. Might potentially create confusion.

**Comment by HauHe** [comment]
Would be great if you could remove them @EmiFej

**Comment by EmiFej** [comment]
Hi @HauHe , I believe they are now removed and added to this PR my default.

**Pull request merged**
